// app/manage-arco-web/src/views/user/login/Login.vue
<script setup lang="ts">
import { login } from "@/composables/auth/login";
import { ref } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();

const loginAuthInfo = ref({
  username: "",
  password: "",
});

const handleLogin = async () => {
  await login(loginAuthInfo.value);
  router.push("/dashboard/view");
};
</script>

<template>
  <div class="login-container">
    <div class="login-sidebar">
      <div class="sidebar-content">
        <h1 class="sidebar-title">Red BlinBlin</h1>
        <h1 class="sidebar-subtitle">后台管理工具</h1>
      </div>
    </div>

    <div class="login-main">
      <div class="login-form-wrapper">
        <div class="login-card">
          <h2 class="login-heading">管理后台用户登录</h2>
          <a-form :model="loginAuthInfo" @submit="handleLogin" layout="vertical">
            <a-form-item field="username">
              <a-input v-model="loginAuthInfo.username" placeholder="用户名" size="large" allow-clear />
            </a-form-item>
            <a-form-item field="password">
              <a-input-password v-model="loginAuthInfo.password" placeholder="密码" size="large" allow-clear />
            </a-form-item>
            <a-form-item>
              <a-button type="primary" html-type="submit" size="large" long>登录</a-button>
            </a-form-item>
          </a-form>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.login-container {
  display: flex;
  min-height: 100vh;
}

.login-sidebar {
  display: none;
  width: 20%;
  background: linear-gradient(to bottom right, #334155, #0f172a);
  align-items: center;
  justify-content: center;
}

@media (min-width: 1024px) {
  .login-sidebar {
    display: flex;
  }
}

.sidebar-content {
  text-align: center;
  color: white;
}

.sidebar-title {
  font-size: 2.25rem;
  font-weight: 700;
  margin-bottom: 1rem;
}

.sidebar-subtitle {
  font-size: 1.875rem;
  font-weight: 700;
  margin-bottom: 1rem;
}

.login-main {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #f9fafb;
}

.login-form-wrapper {
  width: 100%;
  max-width: 32rem;
  padding: 0 2rem;
}

.login-card {
  background: white;
  padding: 2rem;
  box-shadow: 1px rgba(0, 0, 0, 0.1);
}

.login-heading {
  font-size: 1.5rem;
  font-weight: 600;
  color: #1f2937;
  margin-bottom: 1.5rem;
}
</style>

// app/manage-web/src/pages/user/login/index.tsx
import { useUserLoginState } from "@app/manage-web/hooks/user";
import { Button, Input } from "@heroui/react";
import { useState } from "react";
import { useNavigate } from "react-router";

export default function UserLogin() {
  const { fetchUserLogin } = useUserLoginState();

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const navigate = useNavigate();

  const handleLogin = async () => {
    await fetchUserLogin(username, password);
    navigate('/dashboard/view');
  };

  return (
    <div className="flex min-h-screen">
      <div className="hidden lg:flex lg:w-1/5 bg-gradient-to-br from-slate-700 to-slate-900 items-center justify-center">
        <div className="text-center text-white">
          <h1 className="text-4xl font-bold mb-4">Red BlinBlin</h1>
          <h1 className="text-3xl font-bold mb-4">后台管理工具</h1>
        </div>
      </div>

      <div className="flex-1 flex items-center justify-center bg-gray-50">
        <div className="w-full max-w-md px-8">
          <div className="bg-white p-8 rounded-xl shadow-lg lg:w-120">
            <h2 className="text-2xl font-semibold text-gray-800 mb-6">管理后台用户登录</h2>
            <div className="space-y-4">
              <Input
                variant="secondary"
                placeholder="用户名"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="w-full"
              />
              <Input
                type="password"
                variant="secondary"
                placeholder="密码"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full"
              />
              <Button variant="primary" className="w-full mt-2" size="lg" onClick={handleLogin}>登录</Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
